stages:
  - lint
  - plan
  - apply

image: 
  name: hashicorp/terraform:light
  entrypoint: [""]

variables:
  TF_ADDRESS: "https://gitlab.com/api/v4/projects/${PROJECT_ID}/terraform/state/teach-challenge-state"
  backend_config: |
    -backend-config=address=${TF_ADDRESS} \
    -backend-config=lock_address=${TF_ADDRESS}/lock \
    -backend-config=unlock_address=${TF_ADDRESS}/lock \
    -backend-config=username=${TF_USERNAME} \
    -backend-config=password=${TF_PASSWORD} \
    -backend-config=lock_method=POST \
    -backend-config=unlock_method=DELETE \
    -backend-config=retry_wait_min=5

validate:
  stage: lint
  script:
    - terraform --version
    - cd ${CI_PROJECT_DIR}/tf_templates
    - terraform init 
    - terraform validate

plan:
  stage: plan
  script:
    - cd ${CI_PROJECT_DIR}/tf_templates
    - terraform init ${backend_config}
    - terraform plan

apply:
  stage: apply
  when: manual
  script:
    - cd ${CI_PROJECT_DIR}/tf_templates
    - terraform init ${backend_config}
    - terraform apply -auto-approve