stages:
  - download-app
  - lint
  - plan
  - apply
  - destroy

image: 
  name: hashicorp/terraform:light
  entrypoint: [""]

variables: &common_vars
  TF_ADDRESS: "https://gitlab.com/api/v4/projects/${PROJECT_ID}/terraform/state/teach-challenge-state"
  backend_config: >
    -backend-config=address=$TF_ADDRESS 
    -backend-config=lock_address=$TF_ADDRESS/lock 
    -backend-config=unlock_address=$TF_ADDRESS/lock 
    -backend-config=username=${TF_USERNAME} 
    -backend-config=password=${TF_PASSWORD} 
    -backend-config=lock_method=POST 
    -backend-config=unlock_method=DELETE 
    -backend-config=retry_wait_min=5

configure-application:
  stage: download-app
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  variables:
    <<: *common_vars
  script:
  - export DEFAULT_AWS_REGION=${AWS_REGION}
  - asg=$(aws autoscaling describe-auto-scaling-groups)
  - yum install -y jq
  - echo ${asg}
  - ASG=$(aws autoscaling describe-auto-scaling-groups)
  - ASG_INSTANCE_COUNT=$(echo ${ASG} | jq -c '.AutoScalingGroups[] | select(.AutoScalingGroupName | contains("test-asg")) | .Instances | length')
  - echo ${ASG_INSTANCE_COUNT}


# validate:
#   stage: lint
#   variables:
#     <<: *common_vars
#   before_script:
#     - mkdir app && cd app
#     - wget https://github.com/servian/TechChallengeApp/releases/download/v.0.10.0/TechChallengeApp_v.0.10.0_linux64.zip
#     - unzip TechChallengeApp_v.0.10.0_linux64.zip -d ./
#   script:
#     - terraform --version
#     - cd ${CI_PROJECT_DIR}/tf_templates
#     - echo $backend_config
#     - terraform init $backend_config
#     - terraform validate

# plan:
#   stage: plan
#   variables:
#     <<: *common_vars
#   script:
#     - cd ${CI_PROJECT_DIR}/tf_templates
#     - terraform init $backend_config
#     - terraform plan

# apply:
#   stage: apply
#   when: manual
#   variables:
#     <<: *common_vars    
#   script:
#     - cd ${CI_PROJECT_DIR}/tf_templates
#     - terraform init $backend_config
#     - terraform apply -auto-approve

# destroy:
#   stage: destroy
#   when: manual
#   variables:
#     <<: *common_vars
#   script:
#     - cd ${CI_PROJECT_DIR}/tf_templates
#     - terraform init $backend_config
#     - terraform destroy -auto-approve
