stages:
  - lint
  - plan
  - apply

image: 
  name: hashicorp/terraform:latest
  entrypoint: [""]
  
validate:
  stage: lint
  script:
    - terraform --version
    - cd ${CI_COMMIT_DIR}/tf_templates
    - terraform init
    - terraform validate

plan:
  stage: plan
  script:
    - cd ${CI_COMMIT_DIR}/tf_templates
    - terraform init
    - terraform plan

