stages:
  - lint
  - plan
  - apply

image: 
  name: hashicorp/terraform:light
  entrypoint: [""]

validate:
  stage: lint
  script:
    - terraform --version
    - cd ${CI_PROJECT_DIR}/tf_templates
    - terraform init
    - terraform validate

plan:
  stage: plan
  script:
    - cd ${CI_PROJECT_DIR}/tf_templates
    - terraform init
    - terraform plan

apply:
  stage: plan
  script:
    - cd ${CI_PROJECT_DIR}/tf_templates
    - terraform init
    - terraform apply -auto-approve